/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SchedulerApi.h"
#include "Helpers.h"

using namespace server::helper;

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

SchedulerApi::SchedulerApi(std::shared_ptr<Pistache::Rest::Router> rtr) {
  router = rtr;
};

void SchedulerApi::init() { setupRoutes(); }

void SchedulerApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Post(*router, base + "/scheduler/sendTask",
               Routes::bind(&SchedulerApi::send_task_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(
      Routes::bind(&SchedulerApi::scheduler_api_default_handler, this));
}

void SchedulerApi::send_task_handler(const Pistache::Rest::Request &request,
                                     Pistache::Http::ResponseWriter response) {
  // Getting the body param

  Task task;

  try {
    nlohmann::json::parse(request.body()).get_to(task);
    this->send_task(task, response);
  } catch (std::runtime_error &e) {
    // send a 400 error
    response.send(Pistache::Http::Code::Bad_Request, e.what());
    return;
  }
}

void SchedulerApi::scheduler_api_default_handler(
    const Pistache::Rest::Request &request,
    Pistache::Http::ResponseWriter response) {
  response.send(Pistache::Http::Code::Not_Found,
                "The requested method does not exist");
}

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org
