/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SchedulerApi.h
 *
 *
 */

#ifndef SchedulerApi_H_
#define SchedulerApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "Task.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class SchedulerApi {
 public:
  SchedulerApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~SchedulerApi() {}
  void init();

  const std::string base = "";

 private:
  void setupRoutes();

  void send_task_handler(const Pistache::Rest::Request &request,
                         Pistache::Http::ResponseWriter response);
  void scheduler_api_default_handler(const Pistache::Rest::Request &request,
                                     Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  ///
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="task"> (optional)</param>
  virtual void send_task(const Task &task,
                         Pistache::Http::ResponseWriter &response) = 0;
};

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* SchedulerApi_H_ */
