/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ContestFilesId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ContestFilesId::ContestFilesId() {
  m_Input_file_id = 0;
  m_Output_file_id = 0;
  m_Description_file_id = 0;
}

ContestFilesId::~ContestFilesId() {}

void ContestFilesId::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const ContestFilesId& o) {
  j = nlohmann::json();
  j["input_file_id"] = o.m_Input_file_id;
  j["output_file_id"] = o.m_Output_file_id;
  j["description_file_id"] = o.m_Description_file_id;
}

void from_json(const nlohmann::json& j, ContestFilesId& o) {
  j.at("input_file_id").get_to(o.m_Input_file_id);
  j.at("output_file_id").get_to(o.m_Output_file_id);
  j.at("description_file_id").get_to(o.m_Description_file_id);
}

int32_t ContestFilesId::getInputFileId() const { return m_Input_file_id; }
void ContestFilesId::setInputFileId(int32_t const value) {
  m_Input_file_id = value;
}
int32_t ContestFilesId::getOutputFileId() const { return m_Output_file_id; }
void ContestFilesId::setOutputFileId(int32_t const value) {
  m_Output_file_id = value;
}
int32_t ContestFilesId::getDescriptionFileId() const {
  return m_Description_file_id;
}
void ContestFilesId::setDescriptionFileId(int32_t const value) {
  m_Description_file_id = value;
}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
