/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ContestFiles.h
 *
 *
 */

#ifndef ContestFiles_H_
#define ContestFiles_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ContestFiles {
 public:
  ContestFiles();
  virtual ~ContestFiles();

  void validate();

  /////////////////////////////////////////////
  /// ContestFiles members

  /// <summary>
  ///
  /// </summary>
  std::string getInputFile() const;
  void setInputFile(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getOutputFile() const;
  void setOutputFile(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getDescriptionFile() const;
  void setDescriptionFile(std::string const& value);

  friend void to_json(nlohmann::json& j, const ContestFiles& o);
  friend void from_json(const nlohmann::json& j, ContestFiles& o);

 protected:
  std::string m_Input_file;

  std::string m_Output_file;

  std::string m_Description_file;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* ContestFiles_H_ */
