/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ContestId.h
 *
 *
 */

#ifndef ContestId_H_
#define ContestId_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ContestId {
 public:
  ContestId();
  virtual ~ContestId();

  void validate();

  /////////////////////////////////////////////
  /// ContestId members

  /// <summary>
  ///
  /// </summary>
  int32_t getContestId() const;
  void setContestId(int32_t const value);

  friend void to_json(nlohmann::json& j, const ContestId& o);
  friend void from_json(const nlohmann::json& j, ContestId& o);

 protected:
  int32_t m_Contest_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* ContestId_H_ */
