/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ContestFiles.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ContestFiles::ContestFiles() {}

ContestFiles::~ContestFiles() {}

void ContestFiles::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const ContestFiles& o) {
  j = nlohmann::json();
  j["input_file"] = o.m_Input_file;
  j["output_file"] = o.m_Output_file;
  j["description_file"] = o.m_Description_file;
}

void from_json(const nlohmann::json& j, ContestFiles& o) {
  j.at("input_file").get_to(o.m_Input_file);
  j.at("output_file").get_to(o.m_Output_file);
  j.at("description_file").get_to(o.m_Description_file);
}

std::string ContestFiles::getInputFile() const { return m_Input_file; }
void ContestFiles::setInputFile(std::string const& value) {
  m_Input_file = value;
}
std::string ContestFiles::getOutputFile() const { return m_Output_file; }
void ContestFiles::setOutputFile(std::string const& value) {
  m_Output_file = value;
}
std::string ContestFiles::getDescriptionFile() const {
  return m_Description_file;
}
void ContestFiles::setDescriptionFile(std::string const& value) {
  m_Description_file = value;
}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
