/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ContestFilesId.h
 *
 *
 */

#ifndef ContestFilesId_H_
#define ContestFilesId_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ContestFilesId {
 public:
  ContestFilesId();
  virtual ~ContestFilesId();

  void validate();

  /////////////////////////////////////////////
  /// ContestFilesId members

  /// <summary>
  ///
  /// </summary>
  int32_t getInputFileId() const;
  void setInputFileId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getOutputFileId() const;
  void setOutputFileId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getDescriptionFileId() const;
  void setDescriptionFileId(int32_t const value);

  friend void to_json(nlohmann::json& j, const ContestFilesId& o);
  friend void from_json(const nlohmann::json& j, ContestFilesId& o);

 protected:
  int32_t m_Input_file_id;

  int32_t m_Output_file_id;

  int32_t m_Description_file_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* ContestFilesId_H_ */
