/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SessionId.h
 *
 *
 */

#ifndef SessionId_H_
#define SessionId_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class SessionId {
 public:
  SessionId();
  virtual ~SessionId();

  void validate();

  /////////////////////////////////////////////
  /// SessionId members

  /// <summary>
  ///
  /// </summary>
  int32_t getSessionId() const;
  void setSessionId(int32_t const value);

  friend void to_json(nlohmann::json& j, const SessionId& o);
  friend void from_json(const nlohmann::json& j, SessionId& o);

 protected:
  int32_t m_Session_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* SessionId_H_ */
