/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SessionId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SessionId::SessionId() { m_Session_id = 0; }

SessionId::~SessionId() {}

void SessionId::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const SessionId& o) {
  j = nlohmann::json();
  j["session_id"] = o.m_Session_id;
}

void from_json(const nlohmann::json& j, SessionId& o) {
  j.at("session_id").get_to(o.m_Session_id);
}

int32_t SessionId::getSessionId() const { return m_Session_id; }
void SessionId::setSessionId(int32_t const value) { m_Session_id = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
