/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SolutionFilesId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SolutionFilesId::SolutionFilesId() {
  m_Log_file_id = 0;
  m_Result_file_id = 0;
}

SolutionFilesId::~SolutionFilesId() {}

void SolutionFilesId::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const SolutionFilesId& o) {
  j = nlohmann::json();
  j["log_file_id"] = o.m_Log_file_id;
  j["result_file_id"] = o.m_Result_file_id;
}

void from_json(const nlohmann::json& j, SolutionFilesId& o) {
  j.at("log_file_id").get_to(o.m_Log_file_id);
  j.at("result_file_id").get_to(o.m_Result_file_id);
}

int32_t SolutionFilesId::getLogFileId() const { return m_Log_file_id; }
void SolutionFilesId::setLogFileId(int32_t const value) {
  m_Log_file_id = value;
}
int32_t SolutionFilesId::getResultFileId() const { return m_Result_file_id; }
void SolutionFilesId::setResultFileId(int32_t const value) {
  m_Result_file_id = value;
}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
