/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Solution.h
 *
 *
 */

#ifndef Solution_H_
#define Solution_H_

#include <nlohmann/json.hpp>
#include "SolutionData.h"
#include "SolutionId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class Solution {
 public:
  Solution();
  virtual ~Solution();

  void validate();

  /////////////////////////////////////////////
  /// Solution members

  /// <summary>
  ///
  /// </summary>
  int32_t getSolutionId() const;
  void setSolutionId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getTaskId() const;
  void setTaskId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getLogFileId() const;
  void setLogFileId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getResultFileId() const;
  void setResultFileId(int32_t const value);

  friend void to_json(nlohmann::json& j, const Solution& o);
  friend void from_json(const nlohmann::json& j, Solution& o);

 protected:
  int32_t m_Solution_id;

  int32_t m_Task_id;

  int32_t m_Log_file_id;

  int32_t m_Result_file_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* Solution_H_ */
