/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SolutionFilesId.h
 *
 *
 */

#ifndef SolutionFilesId_H_
#define SolutionFilesId_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class SolutionFilesId {
 public:
  SolutionFilesId();
  virtual ~SolutionFilesId();

  void validate();

  /////////////////////////////////////////////
  /// SolutionFilesId members

  /// <summary>
  ///
  /// </summary>
  int32_t getLogFileId() const;
  void setLogFileId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getResultFileId() const;
  void setResultFileId(int32_t const value);

  friend void to_json(nlohmann::json& j, const SolutionFilesId& o);
  friend void from_json(const nlohmann::json& j, SolutionFilesId& o);

 protected:
  int32_t m_Log_file_id;

  int32_t m_Result_file_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* SolutionFilesId_H_ */
