/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SolutionFiles.h
 *
 *
 */

#ifndef SolutionFiles_H_
#define SolutionFiles_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class SolutionFiles {
 public:
  SolutionFiles();
  virtual ~SolutionFiles();

  void validate();

  /////////////////////////////////////////////
  /// SolutionFiles members

  /// <summary>
  ///
  /// </summary>
  std::string getLogFile() const;
  void setLogFile(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getResultFile() const;
  void setResultFile(std::string const& value);

  friend void to_json(nlohmann::json& j, const SolutionFiles& o);
  friend void from_json(const nlohmann::json& j, SolutionFiles& o);

 protected:
  std::string m_Log_file;

  std::string m_Result_file;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* SolutionFiles_H_ */
