/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SolutionFiles.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SolutionFiles::SolutionFiles() {}

SolutionFiles::~SolutionFiles() {}

void SolutionFiles::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const SolutionFiles& o) {
  j = nlohmann::json();
  j["log_file"] = o.m_Log_file;
  j["result_file"] = o.m_Result_file;
}

void from_json(const nlohmann::json& j, SolutionFiles& o) {
  j.at("log_file").get_to(o.m_Log_file);
  j.at("result_file").get_to(o.m_Result_file);
}

std::string SolutionFiles::getLogFile() const { return m_Log_file; }
void SolutionFiles::setLogFile(std::string const& value) { m_Log_file = value; }
std::string SolutionFiles::getResultFile() const { return m_Result_file; }
void SolutionFiles::setResultFile(std::string const& value) {
  m_Result_file = value;
}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
