/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Solution.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Solution::Solution() {
  m_Solution_id = 0;
  m_Task_id = 0;
  m_Log_file_id = 0;
  m_Result_file_id = 0;
}

Solution::~Solution() {}

void Solution::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const Solution& o) {
  j = nlohmann::json();
  j["solution_id"] = o.m_Solution_id;
  j["task_id"] = o.m_Task_id;
  j["log_file_id"] = o.m_Log_file_id;
  j["result_file_id"] = o.m_Result_file_id;
}

void from_json(const nlohmann::json& j, Solution& o) {
  j.at("solution_id").get_to(o.m_Solution_id);
  j.at("task_id").get_to(o.m_Task_id);
  j.at("log_file_id").get_to(o.m_Log_file_id);
  j.at("result_file_id").get_to(o.m_Result_file_id);
}

int32_t Solution::getSolutionId() const { return m_Solution_id; }
void Solution::setSolutionId(int32_t const value) { m_Solution_id = value; }
int32_t Solution::getTaskId() const { return m_Task_id; }
void Solution::setTaskId(int32_t const value) { m_Task_id = value; }
int32_t Solution::getLogFileId() const { return m_Log_file_id; }
void Solution::setLogFileId(int32_t const value) { m_Log_file_id = value; }
int32_t Solution::getResultFileId() const { return m_Result_file_id; }
void Solution::setResultFileId(int32_t const value) {
  m_Result_file_id = value;
}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
