/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SolutionId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SolutionId::SolutionId() { m_Solution_id = 0; }

SolutionId::~SolutionId() {}

void SolutionId::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const SolutionId& o) {
  j = nlohmann::json();
  j["solution_id"] = o.m_Solution_id;
}

void from_json(const nlohmann::json& j, SolutionId& o) {
  j.at("solution_id").get_to(o.m_Solution_id);
}

int32_t SolutionId::getSolutionId() const { return m_Solution_id; }
void SolutionId::setSolutionId(int32_t const value) { m_Solution_id = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
