/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TaskFileId_allOf.h
 *
 *
 */

#ifndef TaskFileId_allOf_H_
#define TaskFileId_allOf_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class TaskFileId_allOf {
 public:
  TaskFileId_allOf();
  virtual ~TaskFileId_allOf();

  void validate();

  /////////////////////////////////////////////
  /// TaskFileId_allOf members

  /// <summary>
  ///
  /// </summary>
  int32_t getTaskFileId() const;
  void setTaskFileId(int32_t const value);

  friend void to_json(nlohmann::json& j, const TaskFileId_allOf& o);
  friend void from_json(const nlohmann::json& j, TaskFileId_allOf& o);

 protected:
  int32_t m_Task_file_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* TaskFileId_allOf_H_ */
