/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TaskData.h
 *
 *
 */

#ifndef TaskData_H_
#define TaskData_H_

#include <nlohmann/json.hpp>
#include "ContestId.h"
#include "TaskFileId.h"
#include "UserId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class TaskData {
 public:
  TaskData();
  virtual ~TaskData();

  void validate();

  /////////////////////////////////////////////
  /// TaskData members

  /// <summary>
  ///
  /// </summary>
  int32_t getUserId() const;
  void setUserId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getContestId() const;
  void setContestId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getTaskFileId() const;
  void setTaskFileId(int32_t const value);

  friend void to_json(nlohmann::json& j, const TaskData& o);
  friend void from_json(const nlohmann::json& j, TaskData& o);

 protected:
  int32_t m_User_id;

  int32_t m_Contest_id;

  int32_t m_Task_file_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* TaskData_H_ */
