/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TaskFileId_allOf.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

TaskFileId_allOf::TaskFileId_allOf() { m_Task_file_id = 0; }

TaskFileId_allOf::~TaskFileId_allOf() {}

void TaskFileId_allOf::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const TaskFileId_allOf& o) {
  j = nlohmann::json();
  j["task_file_id"] = o.m_Task_file_id;
}

void from_json(const nlohmann::json& j, TaskFileId_allOf& o) {
  j.at("task_file_id").get_to(o.m_Task_file_id);
}

int32_t TaskFileId_allOf::getTaskFileId() const { return m_Task_file_id; }
void TaskFileId_allOf::setTaskFileId(int32_t const value) {
  m_Task_file_id = value;
}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
