/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TaskFile.h
 *
 *
 */

#ifndef TaskFile_H_
#define TaskFile_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class TaskFile {
 public:
  TaskFile();
  virtual ~TaskFile();

  void validate();

  /////////////////////////////////////////////
  /// TaskFile members

  /// <summary>
  ///
  /// </summary>
  std::string getTaskFile() const;
  void setTaskFile(std::string const& value);

  friend void to_json(nlohmann::json& j, const TaskFile& o);
  friend void from_json(const nlohmann::json& j, TaskFile& o);

 protected:
  std::string m_Task_file;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* TaskFile_H_ */
