/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TaskFile.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

TaskFile::TaskFile() {}

TaskFile::~TaskFile() {}

void TaskFile::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const TaskFile& o) {
  j = nlohmann::json();
  j["task_file"] = o.m_Task_file;
}

void from_json(const nlohmann::json& j, TaskFile& o) {
  j.at("task_file").get_to(o.m_Task_file);
}

std::string TaskFile::getTaskFile() const { return m_Task_file; }
void TaskFile::setTaskFile(std::string const& value) { m_Task_file = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
