/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Task.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Task::Task() {
  m_Task_id = 0;
  m_User_id = 0;
  m_Contest_id = 0;
  m_Task_file_id = 0;
}

Task::~Task() {}

void Task::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const Task& o) {
  j = nlohmann::json();
  j["task_id"] = o.m_Task_id;
  j["user_id"] = o.m_User_id;
  j["contest_id"] = o.m_Contest_id;
  j["task_file_id"] = o.m_Task_file_id;
}

void from_json(const nlohmann::json& j, Task& o) {
  j.at("task_id").get_to(o.m_Task_id);
  j.at("user_id").get_to(o.m_User_id);
  j.at("contest_id").get_to(o.m_Contest_id);
  j.at("task_file_id").get_to(o.m_Task_file_id);
}

int32_t Task::getTaskId() const { return m_Task_id; }
void Task::setTaskId(int32_t const value) { m_Task_id = value; }
int32_t Task::getUserId() const { return m_User_id; }
void Task::setUserId(int32_t const value) { m_User_id = value; }
int32_t Task::getContestId() const { return m_Contest_id; }
void Task::setContestId(int32_t const value) { m_Contest_id = value; }
int32_t Task::getTaskFileId() const { return m_Task_file_id; }
void Task::setTaskFileId(int32_t const value) { m_Task_file_id = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
