/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TaskData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

TaskData::TaskData() {
  m_User_id = 0;
  m_Contest_id = 0;
  m_Task_file_id = 0;
}

TaskData::~TaskData() {}

void TaskData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const TaskData& o) {
  j = nlohmann::json();
  j["user_id"] = o.m_User_id;
  j["contest_id"] = o.m_Contest_id;
  j["task_file_id"] = o.m_Task_file_id;
}

void from_json(const nlohmann::json& j, TaskData& o) {
  j.at("user_id").get_to(o.m_User_id);
  j.at("contest_id").get_to(o.m_Contest_id);
  j.at("task_file_id").get_to(o.m_Task_file_id);
}

int32_t TaskData::getUserId() const { return m_User_id; }
void TaskData::setUserId(int32_t const value) { m_User_id = value; }
int32_t TaskData::getContestId() const { return m_Contest_id; }
void TaskData::setContestId(int32_t const value) { m_Contest_id = value; }
int32_t TaskData::getTaskFileId() const { return m_Task_file_id; }
void TaskData::setTaskFileId(int32_t const value) { m_Task_file_id = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
