/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UserSessionId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

UserSessionId::UserSessionId() {
  m_User_id = 0;
  m_Session_id = 0;
}

UserSessionId::~UserSessionId() {}

void UserSessionId::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const UserSessionId& o) {
  j = nlohmann::json();
  j["user_id"] = o.m_User_id;
  j["session_id"] = o.m_Session_id;
}

void from_json(const nlohmann::json& j, UserSessionId& o) {
  j.at("user_id").get_to(o.m_User_id);
  j.at("session_id").get_to(o.m_Session_id);
}

int32_t UserSessionId::getUserId() const { return m_User_id; }
void UserSessionId::setUserId(int32_t const value) { m_User_id = value; }
int32_t UserSessionId::getSessionId() const { return m_Session_id; }
void UserSessionId::setSessionId(int32_t const value) { m_Session_id = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
