/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UserId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

UserId::UserId() { m_User_id = 0; }

UserId::~UserId() {}

void UserId::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const UserId& o) {
  j = nlohmann::json();
  j["user_id"] = o.m_User_id;
}

void from_json(const nlohmann::json& j, UserId& o) {
  j.at("user_id").get_to(o.m_User_id);
}

int32_t UserId::getUserId() const { return m_User_id; }
void UserId::setUserId(int32_t const value) { m_User_id = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
