/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * User.h
 *
 *
 */

#ifndef User_H_
#define User_H_

#include <nlohmann/json.hpp>
#include <string>
#include "UserData.h"
#include "UserId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class User {
 public:
  User();
  virtual ~User();

  void validate();

  /////////////////////////////////////////////
  /// User members

  /// <summary>
  ///
  /// </summary>
  int32_t getUserId() const;
  void setUserId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  std::string getUserPassword() const;
  void setUserPassword(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getUserName() const;
  void setUserName(std::string const& value);

  friend void to_json(nlohmann::json& j, const User& o);
  friend void from_json(const nlohmann::json& j, User& o);

 protected:
  int32_t m_User_id;

  std::string m_User_password;

  std::string m_User_name;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* User_H_ */
