/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UserData.h
 *
 *
 */

#ifndef UserData_H_
#define UserData_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class UserData {
 public:
  UserData();
  virtual ~UserData();

  void validate();

  /////////////////////////////////////////////
  /// UserData members

  /// <summary>
  ///
  /// </summary>
  std::string getUserPassword() const;
  void setUserPassword(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getUserName() const;
  void setUserName(std::string const& value);

  friend void to_json(nlohmann::json& j, const UserData& o);
  friend void from_json(const nlohmann::json& j, UserData& o);

 protected:
  std::string m_User_password;

  std::string m_User_name;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* UserData_H_ */
