/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UserId.h
 *
 *
 */

#ifndef UserId_H_
#define UserId_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class UserId {
 public:
  UserId();
  virtual ~UserId();

  void validate();

  /////////////////////////////////////////////
  /// UserId members

  /// <summary>
  ///
  /// </summary>
  int32_t getUserId() const;
  void setUserId(int32_t const value);

  friend void to_json(nlohmann::json& j, const UserId& o);
  friend void from_json(const nlohmann::json& j, UserId& o);

 protected:
  int32_t m_User_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* UserId_H_ */
