/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "User.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

User::User() {
  m_User_id = 0;
  m_User_password = "";
  m_User_name = "";
}

User::~User() {}

void User::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const User& o) {
  j = nlohmann::json();
  j["user_id"] = o.m_User_id;
  j["user_password"] = o.m_User_password;
  j["user_name"] = o.m_User_name;
}

void from_json(const nlohmann::json& j, User& o) {
  j.at("user_id").get_to(o.m_User_id);
  j.at("user_password").get_to(o.m_User_password);
  j.at("user_name").get_to(o.m_User_name);
}

int32_t User::getUserId() const { return m_User_id; }
void User::setUserId(int32_t const value) { m_User_id = value; }
std::string User::getUserPassword() const { return m_User_password; }
void User::setUserPassword(std::string const& value) {
  m_User_password = value;
}
std::string User::getUserName() const { return m_User_name; }
void User::setUserName(std::string const& value) { m_User_name = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
