/**
 * TP-Contest Worker
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Slot.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Slot_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Slot_H_

#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class Slot : public ModelBase {
 public:
  Slot();
  virtual ~Slot();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  void fromJson(const web::json::value& json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t& namePrefix) const override;
  void fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) override;

  /////////////////////////////////////////////
  /// Slot members

  /// <summary>
  ///
  /// </summary>
  utility::string_t getName() const;

  void setName(const utility::string_t& value);

  /// <summary>
  ///
  /// </summary>
  int32_t getCount() const;

  void setCount(int32_t value);

 protected:
  utility::string_t m_Name;
  int32_t m_Count;
};

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Slot_H_ */
