/**
 * TP-Contest Worker
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Task.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Task_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Task_H_

#include "ModelBase.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class Task : public ModelBase {
 public:
  Task();
  virtual ~Task();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  void fromJson(const web::json::value& json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t& namePrefix) const override;
  void fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) override;

  /////////////////////////////////////////////
  /// Task members

  /// <summary>
  ///
  /// </summary>
  int32_t getTaskId() const;

  void setTaskId(int32_t value);

  /// <summary>
  ///
  /// </summary>
  int32_t getUserId() const;

  void setUserId(int32_t value);

  /// <summary>
  ///
  /// </summary>
  int32_t getContestId() const;

  void setContestId(int32_t value);

  /// <summary>
  ///
  /// </summary>
  int32_t getTaskFileId() const;

  void setTaskFileId(int32_t value);

 protected:
  int32_t m_Task_id;
  int32_t m_User_id;
  int32_t m_Contest_id;
  int32_t m_Task_file_id;
};

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Task_H_ */
